### ISSUE TITLE
Suggestion: Add the different witcher gear levels

### ISSUE THREAD

**Issue by ThereIsNo-E** [MMagg-dev/Guide_Checklist_The_Witcher_3#1]
I've just come across this fantastic app which has been super useful for tracking progress. The main thing I've found to be missing is the different levels for all the witcher gear sets (standard, enhanced, superior etc.). Would be great if this could be added if this app is still maintained.

**Comment by MMagg-dev** [comment]
Thank you for the kind words and the suggestion. We will add the gear sets in the upcoming update.
